### ISSUE TITLE
Liveblog does not update automatically in Plone 5

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.liveblog#21]
Seems we have a problem with the way we are generating the URL as it's searching for `http://localhost:8080/Plone/recent-updates` instead of `http://localhost:8080/Plone/liveblog/recent-updates`:

![selection_067](https://cloud.githubusercontent.com/assets/341393/14958919/6c1cbf16-1063-11e6-9f42-417c2861e88c.png)

**Comment by hvelarde** [comment]
Seems the problem is related with the CSRF protection; I see the following output on the instance log:

```python
AttributeError: 'NoneType' object has no attribute 'getroottree'
2016-05-02 12:45:17 ERROR plone.transformchain Unexpected error whilst trying to apply transform chain
Traceback (most recent call last):
  File "/home/hvelarde/.buildout/eggs/plone.transformchain-1.1.0-py2.7.egg/plone/transformchain/transformer.py", line 43, in __call__
    newResult = handler.transformIterable(result, encoding)
  File "/home/hvelarde/.buildout/eggs/plone.protect-3.0.18-py2.7.egg/plone/protect/auto.py", line 163, in transformIterable
    return self.transform(result, encoding)
  File "/home/hvelarde/.buildout/eggs/plone.protect-3.0.18-py2.7.egg/plone/protect/auto.py", line 264, in transform
    result = self.parseTree(result, encoding)
  File "/home/hvelarde/.buildout/eggs/plone.protect-3.0.18-py2.7.egg/plone/protect/auto.py", line 91, in parseTree
    result, pretty_print=False, encoding=encoding)
  File "/home/hvelarde/.buildout/eggs/repoze.xmliter-0.6-py2.7.egg/repoze/xmliter/utils.py", line 32, in getHTMLSerializer
    doctype=doctype,
  File "/home/hvelarde/.buildout/eggs/repoze.xmliter-0.6-py2.7.egg/repoze/xmliter/utils.py", line 19, in getXMLSerializer
    return XMLSerializer(root.getroottree(), serializer, pretty_print, doctype=doctype)
AttributeError: 'NoneType' object has no attribute 'getroottree'
```
